language: csharp
solution: DotNetMockServerClient.sln
mono: none
dist: bionic
before_install:
  - wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-5.0
  - sudo apt-get install -y aspnetcore-runtime-5.0
script:
- dotnet test --filter "Category=MockTests"
- dotnet build -c Release
- dotnet pack -c Release
